steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/adk-rag-backend', '.']

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/adk-rag-backend']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'adk-rag-backend',
        '--image', 'gcr.io/$PROJECT_ID/adk-rag-backend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'PROJECT_ID=adk-rag-poc-464605,LOCATION=us-central1,GOOGLE_GENAI_USE_VERTEXAI=True'
      ]
images:
  - 'gcr.io/$PROJECT_ID/adk-rag-backend'
