steps:
  # Step 1: Build the Docker image from backend directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'backend/Dockerfile',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-rag-backend/adk-rag-backend',
        'backend'
      ]

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/adk-rag-backend/adk-rag-backend'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'adk-rag-backend',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-rag-backend/adk-rag-backend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'PROJECT_ID=adk-rag-poc-464605,LOCATION=us-central1,GOOGLE_GENAI_USE_VERTEXAI=True'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-rag-backend/adk-rag-backend'

options:
  logging: CLOUD_LOGGING_ONLY
